version: "3.8"

services:
  # Database PostgreSQL
  db:
    image: postgres:15-alpine
    container_name: paket_data_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: paket_data_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Aplikasi Go
  app:
    build: .
    container_name: paket_data_api
    restart: always
    ports:
      - "3000:3000"
    environment:
      APP_PORT: 3000
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: paket_data_db
    depends_on:
      - db

volumes:
  postgres_data:
